export default {
    SET_RATING: 'SET_RATING',
    SET_FEEDBACK_COMMENT: 'SET_FEEDBACK_COMMENT',
    SET_MODAL_REPORT_VISIBLE: 'SET_MODAL_REPORT_VISIBLE',
    GET_REPORT_TYPE: 'GET_REPORT_TYPE',
    SET_REPORT_COMMENT: 'SET_REPORT_COMMENT',
    SET_REPORT_TYPE: 'SET_REPORT_TYPE',
    GET_BOOKING_DETAILS: 'GET_BOOKING_DETAILS',
    RESET_FEEDBACK_STATE: 'RESET_FEEDBACK_STATE',
    SET_PENALTIES_PAID: 'SET_PENALTIES_PAID',
    MARK_AS_PAID: 'MARK_AS_PAID'
}