export default {
    GET_HANDYMAN_CURRENT_LOCATION: 'GET_HANDYMAN_CURRENT_LOCATION',
    SET_FIND_MODAL_VISIBLE: 'SET_FIND_MODAL_VISIBLE',
    GET_HANDYMAN_SERVICE: 'GET_HANDYMAN_SERVICE',
    SET_HANDYMAN_SERVICE: 'SET_HANDYMAN_SERVICE', 
    TRACK_HANDYMAN_LOCATION: 'TRACK_HANDYMAN_LOCATION', 
    DELETE_ALL_STATE: 'DELETE_ALL_STATE',
    GET_POINTS: 'GET_POINTS'
}