export default {
    GET_MY_LOCATION: 'GET_MY_LOCATION',
    PROFILE_MODAL_VISIBLE: 'PROFILE_MODAL_VISIBLE',
    CONFIRM_MODAL_VISIBLE: 'CONFIRM_MODAL_VISIBLE',
    GET_USER_PROFILE: 'GET_USER_PROFILE',
    MEET_USERS: 'MEET_USERS',
    GET_DISTANCE: 'GET_DISTANCE',
    SET_MESSAGE: 'SET_MESSAGE',
    READ_MESSAGE: 'READ_MESSAGE',
    SET_REASON_BOX_MESSAGE: 'SET_REASON_BOX_MESSAGE',
    SET_REASON_BOX_VISIBLE: 'SET_REASON_BOX_VISIBLE',
    CANCEL_TRANSACTION: 'CANCEL_TRANSACTION',
    RESET_BOOKING_FORM: 'RESET_BOOKING_FORM',
    SET_TRACK_FARE: 'SET_TRACK_FARE',
    RESET_TRACK_HANDYMAN_STATE: 'RESET_TRACK_HANDYMAN_STATE',
    SET_DISTANCE: 'SET_DISTANCE'
}