export default {
    GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION',
    GET_NEARBY_HANDYMAN: 'GET_NEARBY_HANDYMAN',
    REMOVE_HANDYMAN: 'REMOVE_HANDYMAN',
    RESET_BOTH_STATE: 'RESET_BOTH_STATE',
    SET_REFERRAL: 'SET_REFERRAL',
    SEARCH_PLACE: 'SEARCH_PLACE',
    SET_REFER_ADDRESS: 'SET_REFER_ADDRESS'
};