export default {
    GET_PROFILE: 'GET_PROFILE',
    SET_MODAL_PAYMENT: 'SET_MODAL_PAYMENT',
    SAVE_EDIT: 'SAVE_EDIT',
    SET_PAYMENT_VALUE: 'SET_PAYMENT_VALUE',
    GET_POINTS: 'GET_POINTS',
    DELETE_ALL_STATE: 'DELETE_ALL_STATE'
}