export default {
    SET_LOADING: 'SET_LOADING',
    GET_SERVICES: 'GET_SERVICES',    
    GET_FORM: 'GET_FORM',    
    SET_SERVICE: 'SET_SERVICE',
    SET_CHECKBOX: 'SET_CHECKBOX',
    SET_RADIOBUTTON: 'SET_RADIOBUTTON',
    SET_DROPDOWN: 'SET_DROPDOWN',
    SET_TEXT: 'SET_TEXT',
    SET_REMARKS: 'SET_REMARKS',
    SET_BOOKING: 'SET_BOOKING',
    GET_PENALTY: 'GET_PENALTY',
    SET_BOOKING: 'SET_BOOKING',
    SET_TEXTBOX_CHECK: 'SET_TEXTBOX_CHECK',
    DELETE_ALL_STATE: 'DELETE_ALL_STATE',
    RESET_BOOKING_FORM: 'RESET_BOOKING_FORM',
    SET_TEXTBOX_RADIO: 'SET_TEXTBOX_RADIO',
    SET_REFER_ADDRESS: 'SET_REFER_ADDRESS'
}