export default {
    GET_NOTIFICATION: 'GET_NOTIFICATION',
    SET_NOTIFICATION: 'SET_NOTIFICATION',
    SET_NOTIFICATION_MODAL_VISIBLE: 'SET_NOTIFICATION_MODAL_VISIBLE',
    DELETE_ALL_STATE: 'DELETE_ALL_STATE'
}